modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayTest="IGNORE_ALL_VERSION"
description='''
Client-side recipe wishlist with incremental material expansion for JEI, EMI, and the Vanilla Recipe Book.
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="jei"
mandatory=false
versionRange="[15.56.0.205,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="emi"
mandatory=false
versionRange="[1.1.24,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="create"
mandatory=false
versionRange="[6.0.8,)"
ordering="AFTER"
side="CLIENT"
